name: blosso_mindfulness
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  intl: ^0.18.1
  ionicons: ^0.2.2
  random_avatar: ^0.0.8
  shared_preferences: ^2.2.2
  yaml: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Background/Background1.jpeg
    - assets/Flowers/Flower1.png
    - assets/Flowers/Flower2.png
    - assets/Flowers/Flower3.png
    - assets/Flowers/Flower4.png
    - assets/Flowers/Flower5.png
    - assets/Flowers/Flower6.png
    - assets/Flowers/Flower7.png
  fonts:
    - family: FiraMono
    - fonts:
      - asset: fonts/FiraMono-Bold.ttf
      - asset: fonts/FiraMono-Medium.ttf
      - asset: fonts/FiraMono-Regular.ttf
